[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.95.0"
readme = "README.md"
repository = "https://github.com/hydr/hydr"
keywords = ["proxy", "quic", "websocket", "privacy"]
categories = ["network-programming"]