[package]
name = "hydr-cc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hydr-core = { version = "0.1.0", path = "../hydr-core" }
quinn = "0.11"
quinn-proto = "0.11"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }