[package]
name = "hydr-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
hydr-cc = { version = "0.1.0", path = "../hydr-cc" }
hydr-core = { version = "0.1.0", path = "../hydr-core" }
hydr-transport = { version = "0.1.0", path = "../hydr-transport" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
hydr-server = { path = "../hydr-server" }
